# try ~ except  
# 코드를 시도(실행) 하다가. 에러가 발행하면 해당 에러를 except
# 하는 문장이 있으면 해당 except를 실행하고 
# try~catch문을 종료하고 나머지 코드를 실행


try:
    4 / 0
    print("try 구문을 실행합니다.")
except:
    pass

    

print("정상종료")